###
GET http://localhost:8000/api/v1/mapels

###
POST http://localhost:8000/api/v1/mapels
Content-Type: application/json

{
  "name":"Ilmu Pengetahuan Alam",
  "desc": "Kelas VII"
}

###
GET http://localhost:8000/api/v1/mapels/99754cc2-6c25-48df-8175-f8c9dd6e8a7c

###
PUT http://localhost:8000/api/v1/mapels/99754cc2-6c25-48df-8175-f8c9dd6e8a7c
Content-Type: application/json

{
  "name":"B. Inggris",
  "desc": "Kelas VIII"
}

###
DELETE  http://localhost:8000/api/v1/mapels/99754cc2-6c25-48df-8175-f8c9dd6e8a7c