###
GET http://localhost:8000/api/v1/pesertas

###
POST http://localhost:8000/api/v1/pesertas
Content-Type: application/json

{
  "name":"Andi",
  "username": "andi",
  "password": "andi",
  "ruang": "Kelas VII"
}

###
GET http://localhost:8000/api/v1/pesertas/04d2f25f-b7f0-47ed-805c-1c7913ac5ddf

###
PUT http://localhost:8000/api/v1/pesertas/04d2f25f-b7f0-47ed-805c-1c7913ac5ddf
Content-Type: application/json

{
  "name":"Ahmad",
  "username": "ahmad",
  "password": "password",
  "ruang": "Kelas IX"
}

###
DELETE  http://localhost:8000/api/v1/pesertas/04d2f25f-b7f0-47ed-805c-1c7913ac5ddf